baseURL: https://blog.rjp.pub
languageCode: en-us
title: Ackerman
theme: PaperMod

# enable support of raw html, ref: https://tzhwang.com/2021/08/28/enable-raw-html-in-hugo/
markup:
  goldmark:
    renderer:
      unsafe: true

# search page
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  ShowToc: true
  TocOpen: true
  comments: true
  ShowCodeCopyButtons: true
  ShowReadingTime: true
  homeInfoParams:
    Title: Hi there
    Content: Welcome to my blog
  socialIcons: # 社交平台小图标, 支持列表: https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-icons/
    - name: github
      url: "https://github.com/withrjp"
    - name: email
      url: "mailto:withrjp@gmail.com"